# Shared audited mouse ferroptosis analysis functions for GSE125002 and GSE286387.
# Requires raw gene-level counts and locked mouse gene sets generated by 00_prepare_mouse_gene_sets.R.

mouse_required_pkgs <- c("DESeq2","dplyr","tidyr","readr","tibble","ggplot2","pheatmap","fgsea","AnnotationDbi","org.Mm.eg.db","data.table")
mouse_missing <- mouse_required_pkgs[!vapply(mouse_required_pkgs,requireNamespace,logical(1),quietly=TRUE)]
if(length(mouse_missing)) stop("Missing packages: ",paste(mouse_missing,collapse=", "))
suppressPackageStartupMessages({library(DESeq2);library(dplyr);library(tidyr);library(readr);library(tibble);library(ggplot2);library(pheatmap);library(fgsea);library(AnnotationDbi);library(org.Mm.eg.db)})

standardize_mouse_ids <- function(ids){
  ids <- sub("\\..*$","",as.character(ids)); db <- org.Mm.eg.db
  ens <- grepl("^ENSMUSG",ids,ignore.case=TRUE); ent <- grepl("^[0-9]+$",ids)
  out <- ids
  if(any(ens)){m<-AnnotationDbi::mapIds(db,keys=unique(ids[ens]),keytype="ENSEMBL",column="SYMBOL",multiVals="first");out[ens]<-unname(m[ids[ens]])}
  if(any(ent)){m<-AnnotationDbi::mapIds(db,keys=unique(ids[ent]),keytype="ENTREZID",column="SYMBOL",multiVals="first");out[ent]<-unname(m[ids[ent]])}
  # Reconcile legacy symbols used by older processed-count annotations to the
  # current official mouse nomenclature used by the frozen signatures.
  # NCBI/MGI Gene 353172: official Gars1; Gars is a historical alias.
  out[out=="Gars"] <- "Gars1"
  out
}

load_mouse_signatures <- function(project_dir="cipn-ferroptosis-screening"){
  md <- file.path(project_dir,"config","mouse")
  vf <- file.path(md,"vinik_2024_24_human_to_mouse_locked.csv")
  mf <- file.path(md,"msigdb_Hs_to_mouse_gene_sets_locked.csv")
  manf <- file.path(md,"gene_set_manifest_mouse.csv")
  if(!all(file.exists(c(vf,mf,manf)))) stop("Locked mouse gene sets are missing. Run scripts/00_prepare_mouse_gene_sets.R first, inspect them, then rerun.")
  v<-read_csv(vf,show_col_types=FALSE); m<-read_csv(mf,show_col_types=FALSE); man<-read_csv(manf,show_col_types=FALSE)
  getset<-function(n) unique(m$mouse_gene_symbol[m$signature==n])
  list(signatures=list(VINIK_2024_24_FERROPTOSIS_BIOMARKERS=unique(v$mouse_symbol),GOBP_FERROPTOSIS=getset("GOBP_FERROPTOSIS"),WP_FERROPTOSIS=getset("WP_FERROPTOSIS"),HALLMARK_APOPTOSIS=getset("HALLMARK_APOPTOSIS"),HALLMARK_REACTIVE_OXYGEN_SPECIES_PATHWAY=getset("HALLMARK_REACTIVE_OXYGEN_SPECIES_PATHWAY")),vinik_map=v,manifest=man)
}

run_mouse_ferroptosis_screen <- function(count_mat, meta, accession, result_dir, dataset_note=""){
  dir.create(result_dir,recursive=TRUE,showWarnings=FALSE)
  stopifnot(all(c("sample","group")%in%names(meta)))
  meta<-meta |> mutate(sample=as.character(sample),group=factor(group,levels=c("Vehicle","Oxaliplatin")))
  if(any(is.na(meta$group))||!all(meta$sample%in%colnames(count_mat))) stop("Metadata/count columns do not match.")
  count_mat<-count_mat[,meta$sample,drop=FALSE]; storage.mode(count_mat)<-"numeric"; count_mat<-round(count_mat)
  if(any(!is.finite(count_mat))||any(count_mat<0)) stop("Counts must be finite nonnegative raw counts.")
  # collapse duplicate standardized symbols
  tmp<-as_tibble(count_mat,rownames="gene") |> filter(!is.na(gene),nzchar(gene)) |> group_by(gene) |> summarise(across(everything(),sum),.groups="drop")
  count_mat<-as.matrix(tmp[,-1]);rownames(count_mat)<-tmp$gene;storage.mode(count_mat)<-"integer"
  write_csv(as_tibble(count_mat,rownames="gene"),file.path(result_dir,"count_matrix_gene_symbols.csv"));write_csv(meta,file.path(result_dir,"sample_metadata.csv"))
  keep<-rowSums(count_mat>=10)>=max(3,min(table(meta$group)))
  dds<-DESeqDataSetFromMatrix(countData=count_mat[keep,,drop=FALSE],colData=as.data.frame(meta |> column_to_rownames("sample")),design=~group);dds<-DESeq(dds,quiet=TRUE)
  r<-results(dds,contrast=c("group","Oxaliplatin","Vehicle"),independentFiltering=FALSE)
  de<-tibble(gene=rownames(r),baseMean=r$baseMean,log2FoldChange=r$log2FoldChange,lfcSE=r$lfcSE,stat=r$stat,pvalue=r$pvalue,padj=r$padj)
  write_csv(de,file.path(result_dir,"DE_Oxaliplatin_vs_Vehicle.csv"))
  vsd<-vst(dds,blind=TRUE); vm<-assay(vsd); pc<-prcomp(t(vm)); pct<-as_tibble(pc$x[,1:2,drop=FALSE],rownames="sample") |> left_join(meta,by="sample");write_csv(pct,file.path(result_dir,"pca_coordinates.csv"))
  p<-ggplot(pct,aes(PC1,PC2,shape=group))+geom_point(size=3)+theme_bw()+labs(title=paste(accession,"mouse DRG -- VST PCA"));ggsave(file.path(result_dir,"pca.png"),p,width=7,height=5,dpi=180)
  png(file.path(result_dir,"sample_correlation.png"),1600,1400,res=180);pheatmap(cor(vm),main=paste(accession,"VST sample correlation"));dev.off()
  qc<-tibble(sample=colnames(count_mat),library_size=colSums(count_mat),detected_genes=colSums(count_mat>0),genes_count_ge_10=colSums(count_mat>=10)) |> left_join(meta,by="sample");write_csv(qc,file.path(result_dir,"library_qc.csv"))
  gs<-load_mouse_signatures(); sigs<-gs$signatures
  audit<-bind_rows(lapply(names(sigs),function(n)tibble(signature=n,gene=unique(sigs[[n]])))) |> mutate(present_in_analysis=gene%in%rownames(dds));write_csv(audit,file.path(result_dir,"signature_members_used.csv"));write_csv(gs$manifest,file.path(result_dir,"gene_set_manifest_used.csv"));write_csv(gs$vinik_map,file.path(result_dir,"vinik24_ortholog_mapping.csv"))
  ranks<-de |> filter(is.finite(stat),!is.na(gene),nzchar(gene)) |> distinct(gene,.keep_all=TRUE);rv<-ranks$stat;names(rv)<-ranks$gene;rv<-sort(rv,decreasing=TRUE)
  fg<-fgseaMultilevel(pathways=sigs,stats=rv,minSize=5,maxSize=500,eps=0) |> as_tibble() |> arrange(padj) |> mutate(contrast="Oxaliplatin_vs_Vehicle",leadingEdge=vapply(leadingEdge,paste,collapse=";",FUN.VALUE=character(1)))
  write_csv(fg,file.path(result_dir,"gsea_all_signatures.csv"))
  z<-t(scale(t(vm))); z[!is.finite(z)]<-NA_real_
  score<-bind_rows(lapply(names(sigs),function(n){g<-intersect(sigs[[n]],rownames(z));tibble(sample=colnames(z),signature=n,score=colMeans(z[g,,drop=FALSE],na.rm=TRUE),n_genes=length(g))})) |> left_join(meta,by="sample");write_csv(score,file.path(result_dir,"sample_level_signature_scores.csv"))
  tests<-score |> group_by(signature) |> summarise(vehicle_mean=mean(score[group=="Vehicle"]),treated_mean=mean(score[group=="Oxaliplatin"]),difference=treated_mean-vehicle_mean,t_pvalue=tryCatch(t.test(score~group)$p.value,error=function(e)NA_real_),wilcoxon_pvalue=tryCatch(wilcox.test(score~group,exact=FALSE)$p.value,error=function(e)NA_real_),.groups="drop") |> mutate(t_FDR=p.adjust(t_pvalue,"BH"),wilcoxon_FDR=p.adjust(wilcoxon_pvalue,"BH"));write_csv(tests,file.path(result_dir,"sample_level_score_tests.csv"))
  mech<-c("Acsl4","Lpcat3","Gpx4","Slc7a11","Tfrc","Ncoa4","Fth1","Ftl1","Hmox1","Aifm2","Dh odh","Gch1","Por");mech[mech=="Dh odh"]<-"Dhodh"
  mt<-de |> filter(gene%in%mech) |> arrange(padj);write_csv(mt,file.path(result_dir,"mechanistic_panel_effects.csv"))
  lookup<-function(n,col){x<-fg[fg$pathway==n,,drop=FALSE];if(nrow(x))x[[col]][1] else NA_real_}
  vin_fdr<-lookup("VINIK_2024_24_FERROPTOSIS_BIOMARKERS","padj");vin_nes<-lookup("VINIK_2024_24_FERROPTOSIS_BIOMARKERS","NES");go_fdr<-lookup("GOBP_FERROPTOSIS","padj");wp_fdr<-lookup("WP_FERROPTOSIS","padj");apo_fdr<-lookup("HALLMARK_APOPTOSIS","padj");ros_fdr<-lookup("HALLMARK_REACTIVE_OXYGEN_SPECIES_PATHWAY","padj")
  label<-if(is.finite(vin_fdr)&&vin_fdr<.05&&vin_nes>0&&((is.finite(go_fdr)&&go_fdr<.05)||(is.finite(wp_fdr)&&wp_fdr<.05)))"STRONG_SUPPORT" else if(is.finite(vin_fdr)&&vin_fdr<.05&&vin_nes>0)"SUGGESTIVE_SUPPORT" else "NO_TRANSCRIPTOMIC_SUPPORT"
  ros_nes<-lookup("HALLMARK_REACTIVE_OXYGEN_SPECIES_PATHWAY","NES")
  ros_label<-if(is.finite(ros_fdr)&&ros_fdr<.05&&is.finite(ros_nes)&&ros_nes>0)"POSITIVE_ROS_ENRICHMENT" else if(is.finite(ros_fdr)&&ros_fdr<.05&&is.finite(ros_nes)&&ros_nes<0)"NEGATIVE_ROS_ENRICHMENT" else "NO_SIGNIFICANT_ROS_ENRICHMENT"
  ev<-tibble(dataset=accession,species="Mus musculus",tissue="DRG",contrast="Oxaliplatin_vs_Vehicle",ferroptosis_evidence=label,apoptosis_context=ifelse(is.finite(apo_fdr)&&apo_fdr<.05,"APOPTOSIS_COINCIDENT","NO_SIGNIFICANT_APOPTOSIS_ENRICHMENT"),ros_context=ros_label,note=dataset_note)
  write_csv(ev,file.path(result_dir,"evidence_summary.csv"))
  writeLines(c(paste0("Dataset: ",accession),"Species: Mus musculus","Tissue: dorsal root ganglion","Contrast: Oxaliplatin vs Vehicle",paste0("Dataset note: ",dataset_note),paste0("Genes in reconstructed matrix: ",nrow(count_mat)),paste0("Genes retained for DESeq2: ",nrow(dds)),paste0("Vinik present after filter: ",sum(audit$signature=="VINIK_2024_24_FERROPTOSIS_BIOMARKERS" & audit$present_in_analysis),"/24"),paste0("Evidence label: ",label),"Boundary: bulk RNA-seq can detect ferroptosis-associated transcriptional features but cannot prove ferroptotic cell death or identify the responding cell type."),file.path(result_dir,"analysis_summary.txt"))
  writeLines(capture.output(sessionInfo()),file.path(result_dir,"sessionInfo.txt"));invisible(list(de=de,gsea=fg,evidence=ev))
}
