#!/usr/bin/env Rscript

# GSE247883 — independent Fer-1 rescue replication for the ferroptosis-only model
#
# Input:
#   Salmon quant.sf files generated by 02b_GSE247883_salmon_quant.ps1
#   Frozen GSE182638 discovery candidates from local primary-rescue results
#
# Key rule:
#   GSE247883 is a REPLICATION dataset. It must not re-select discovery genes.
#
# Run from repository root:
#   source("ferroptosis-only/scripts/02_GSE247883_rescue_replication.R")

required_pkgs <- c(
  "DESeq2", "ashr", "dplyr", "tidyr", "readr", "tibble",
  "tximport", "ggplot2", "pheatmap", "jsonlite"
)

missing_pkgs <- required_pkgs[
  !vapply(required_pkgs, requireNamespace, logical(1), quietly = TRUE)
]

if (length(missing_pkgs) > 0) {
  stop(
    "Missing required R packages: ",
    paste(missing_pkgs, collapse = ", "),
    "\nInstall them before running this script."
  )
}

suppressPackageStartupMessages({
  library(DESeq2)
  library(ashr)
  library(dplyr)
  library(tidyr)
  library(readr)
  library(tibble)
  library(tximport)
  library(ggplot2)
  library(pheatmap)
  library(jsonlite)
})

source("R/evidence_functions.R")

accession <- "GSE247883"
sample_file <- file.path(
  "ferroptosis-only", "config", "GSE247883_samples.csv"
)
quant_root <- file.path(
  "ferroptosis-only", "data", "processed", accession, "salmon"
)
reference_fasta <- file.path(
  "ferroptosis-only", "data", "reference", "ensembl101",
  "Homo_sapiens.GRCh38.cdna.all.fa.gz"
)
primary_candidate_file <- file.path(
  "ferroptosis-only", "results", "GSE182638",
  "GSE182638_empirical_ESR_candidates.csv"
)
result_dir <- file.path(
  "ferroptosis-only", "results", accession
)

dir.create(result_dir, recursive = TRUE, showWarnings = FALSE)

message("[1/9] Loading locked sample metadata...")

meta <- readr::read_csv(sample_file, show_col_types = FALSE) %>%
  mutate(
    condition = factor(
      condition,
      levels = c("DMSO", "RSL3_Fer1", "RSL3")
    ),
    replicate = factor(replicate)
  )

design_check <- meta %>%
  count(condition, name = "n")

if (
  nrow(meta) != 9 ||
  nrow(design_check) != 3 ||
  any(design_check$n != 3)
) {
  stop("GSE247883 metadata does not match the locked 3 x 3 design.")
}

write_csv(meta, file.path(result_dir, "sample_metadata_locked.csv"))

message("[2/9] Checking Salmon quantification files...")

quant_files <- file.path(quant_root, meta$gsm, "quant.sf")
names(quant_files) <- meta$gsm

if (!all(file.exists(quant_files))) {
  missing <- names(quant_files)[!file.exists(quant_files)]
  stop(
    "Missing Salmon quant.sf files for: ",
    paste(missing, collapse = ", "),
    "\nRun 02a and 02b before this R script."
  )
}

if (!file.exists(reference_fasta)) {
  stop("Missing Ensembl release 101 cDNA FASTA used for Salmon indexing.")
}

message("[3/9] Building transcript-to-gene map from the exact Ensembl FASTA...")

extract_fasta_tx2gene <- function(path, chunk_size = 50000L) {
  con <- gzfile(path, open = "rt")
  on.exit(close(con), add = TRUE)

  chunks <- list()
  k <- 1L

  repeat {
    x <- readLines(con, n = chunk_size, warn = FALSE)
    if (length(x) == 0) break

    h <- x[startsWith(x, ">")]
    if (length(h) == 0) next

    tx <- sub("^>([^ ]+).*", "\\1", h)

    has_symbol <- grepl(" gene_symbol:[^ ]+", h)
    symbol <- rep(NA_character_, length(h))
    symbol[has_symbol] <- sub(
      ".* gene_symbol:([^ ]+).*",
      "\\1",
      h[has_symbol]
    )

    has_gene <- grepl(" gene:[^ ]+", h)
    gene_id <- rep(NA_character_, length(h))
    gene_id[has_gene] <- sub(
      ".* gene:([^ ]+).*",
      "\\1",
      h[has_gene]
    )

    gene_id_clean <- sub("\\.[0-9]+$", "", gene_id)
    gene <- ifelse(
      !is.na(symbol) & nzchar(symbol),
      symbol,
      gene_id_clean
    )

    chunks[[k]] <- tibble(
      TXNAME = tx,
      GENE = gene
    )
    k <- k + 1L
  }

  bind_rows(chunks) %>%
    filter(
      !is.na(TXNAME), nzchar(TXNAME),
      !is.na(GENE), nzchar(GENE)
    ) %>%
    distinct(TXNAME, .keep_all = TRUE)
}

tx2gene <- extract_fasta_tx2gene(reference_fasta)

if (nrow(tx2gene) < 50000) {
  stop("Transcript-to-gene map is unexpectedly small.")
}

message("[4/9] Importing Salmon estimates and running QC...")

txi <- tximport::tximport(
  quant_files,
  type = "salmon",
  tx2gene = tx2gene,
  ignoreTxVersion = FALSE,
  countsFromAbundance = "no"
)

coldata <- as.data.frame(meta)
rownames(coldata) <- coldata$gsm

dds <- DESeq2::DESeqDataSetFromTximport(
  txi = txi,
  colData = coldata,
  design = ~ condition
)

keep <- rowSums(DESeq2::counts(dds) >= 10) >= 3
dds <- dds[keep, ]

dds <- DESeq2::DESeq(dds, quiet = TRUE)

vsd <- DESeq2::vst(dds, blind = TRUE)
pca <- prcomp(t(SummarizedExperiment::assay(vsd)))

pca_tbl <- as_tibble(
  pca$x[, 1:2, drop = FALSE],
  rownames = "gsm"
) %>%
  left_join(meta, by = "gsm")

write_csv(
  pca_tbl,
  file.path(result_dir, "vst_pca_coordinates.csv")
)

p <- ggplot(pca_tbl, aes(PC1, PC2, shape = condition)) +
  geom_point(size = 3) +
  theme_bw() +
  labs(title = "GSE247883 VST PCA")

ggsave(
  file.path(result_dir, "vst_pca.png"),
  p,
  width = 7,
  height = 5,
  dpi = 180
)

corr <- cor(SummarizedExperiment::assay(vsd), method = "pearson")
png(
  file.path(result_dir, "vst_sample_correlation.png"),
  width = 1600,
  height = 1400,
  res = 180
)
pheatmap::pheatmap(corr, main = "GSE247883 VST sample correlation")
dev.off()

salmon_qc <- lapply(meta$gsm, function(gsm) {
  info_file <- file.path(
    quant_root, gsm, "aux_info", "meta_info.json"
  )

  info <- jsonlite::fromJSON(info_file)

  tibble(
    gsm = gsm,
    num_processed = info$num_processed,
    num_mapped = info$num_mapped,
    percent_mapped = info$percent_mapped
  )
}) %>%
  bind_rows() %>%
  left_join(meta, by = "gsm")

write_csv(
  salmon_qc,
  file.path(result_dir, "salmon_mapping_qc.csv")
)

message("[5/9] Estimating RSL3 induction and Fer-1 rescue effects...")

contrasts <- list(
  RSL3_vs_DMSO = c("condition", "RSL3", "DMSO"),
  RSL3_vs_RSL3_Fer1 = c("condition", "RSL3", "RSL3_Fer1")
)

effects <- lapply(names(contrasts), function(id) {
  ashr_effect_from_contrast(dds, contrasts[[id]]) %>%
    mutate(
      accession = accession,
      contrast_id = id
    )
}) %>%
  bind_rows()

write_csv(
  effects,
  file.path(result_dir, "per_contrast_effects_all_genes.csv")
)

message("[6/9] Reporting mechanistic genes without imposing causal sign on acute RNA response...")

fpt_universe <- read_csv(
  file.path(
    "ferroptosis-only",
    "config",
    "ferroptosis_master_gene_universe.csv"
  ),
  show_col_types = FALSE
)

mechanistic_effects <- effects %>%
  inner_join(
    fpt_universe %>%
      dplyr::select(
        gene, module, role, provisional_status,
        direction_for_rna, evidence_tier, mechanistic_prior_M
      ),
    by = "gene"
  )

write_csv(
  mechanistic_effects,
  file.path(result_dir, "mechanistic_genes_acute_RNA_effects.csv")
)

mechanistic_unsigned <- effects %>%
  group_by(contrast_id) %>%
  add_effect_magnitude() %>%
  ungroup() %>%
  mutate(unsigned_strength = magnitude * confidence) %>%
  inner_join(
    fpt_universe %>%
      dplyr::select(
        gene, module, role, provisional_status,
        evidence_tier, mechanistic_prior_M
      ),
    by = "gene"
  ) %>%
  dplyr::select(
    gene, module, role, provisional_status,
    evidence_tier, mechanistic_prior_M,
    contrast_id, beta, lfsr, unsigned_strength
  ) %>%
  pivot_wider(
    names_from = contrast_id,
    values_from = c(beta, lfsr, unsigned_strength)
  ) %>%
  mutate(
    acute_same_direction =
      is.finite(beta_RSL3_vs_DMSO) &
      is.finite(beta_RSL3_vs_RSL3_Fer1) &
      beta_RSL3_vs_DMSO != 0 &
      beta_RSL3_vs_RSL3_Fer1 != 0 &
      sign(beta_RSL3_vs_DMSO) ==
        sign(beta_RSL3_vs_RSL3_Fer1),
    acute_rescue_strength = ifelse(
      acute_same_direction,
      pmin(
        unsigned_strength_RSL3_vs_DMSO,
        unsigned_strength_RSL3_vs_RSL3_Fer1
      ),
      0
    ),
    acute_response_direction = ifelse(
      acute_same_direction,
      sign(beta_RSL3_vs_DMSO),
      0
    )
  )

write_csv(
  mechanistic_unsigned,
  file.path(result_dir, "mechanistic_genes_rescue_concordance_descriptive.csv")
)

message("[7/9] Freezing GSE182638 discovery candidates...")

if (!file.exists(primary_candidate_file)) {
  stop(
    "Missing primary discovery result: ",
    primary_candidate_file,
    "\nRun GSE182638 first. GSE247883 is not allowed to create a replacement discovery set."
  )
}

primary <- read_csv(
  primary_candidate_file,
  show_col_types = FALSE
)

frozen <- primary %>%
  filter(
    cross_cell_direction_agreement == TRUE,
    is.finite(study_signed_rescue_score),
    study_signed_rescue_score != 0
  ) %>%
  mutate(
    discovery_direction = sign(study_signed_rescue_score)
  ) %>%
  dplyr::select(
    gene,
    discovery_direction,
    study_signed_rescue_score,
    study_rescue_strength,
    MM1R_signed,
    MM1S_signed
  )

if (nrow(frozen) == 0) {
  stop("Frozen GSE182638 discovery set is empty.")
}

snapshot_file <- file.path(
  result_dir,
  "GSE182638_ESR_discovery_snapshot.csv"
)
write_csv(frozen, snapshot_file)

writeLines(
  paste0(
    "MD5 ",
    unname(tools::md5sum(snapshot_file))
  ),
  file.path(
    result_dir,
    "GSE182638_ESR_discovery_snapshot.md5.txt"
  )
)

message("[8/9] Testing frozen candidates for independent rescue replication...")

dictionary <- frozen %>%
  transmute(
    gene,
    direction = discovery_direction
  )

induction_e <- effects %>%
  filter(contrast_id == "RSL3_vs_DMSO") %>%
  score_dictionary_genes(dictionary) %>%
  dplyr::select(
    gene,
    e_induction = e,
    beta_induction = beta,
    lfsr_induction = lfsr
  )

rescue_e <- effects %>%
  filter(contrast_id == "RSL3_vs_RSL3_Fer1") %>%
  score_dictionary_genes(dictionary) %>%
  dplyr::select(
    gene,
    e_reversal = e,
    beta_reversal = beta,
    lfsr_reversal = lfsr
  )

replication <- frozen %>%
  left_join(induction_e, by = "gene") %>%
  left_join(rescue_e, by = "gene") %>%
  mutate(
    replication_e = rescue_validated_evidence(
      e_induction,
      e_reversal
    ),
    replication_status = case_when(
      !is.finite(replication_e) ~ "NOT_TESTABLE",
      replication_e > 0 ~ "SUPPORTS_DISCOVERY_DIRECTION",
      replication_e < 0 ~ "CONTRADICTS_DISCOVERY_DIRECTION",
      TRUE ~ "NO_DIRECTIONAL_EVIDENCE"
    )
  ) %>%
  arrange(desc(replication_e))

write_csv(
  replication,
  file.path(
    result_dir,
    "GSE247883_frozen_ESR_candidate_replication.csv"
  )
)

message("[9/9] Writing audit summary...")

n_support <- sum(
  replication$replication_status ==
    "SUPPORTS_DISCOVERY_DIRECTION",
  na.rm = TRUE
)
n_contradict <- sum(
  replication$replication_status ==
    "CONTRADICTS_DISCOVERY_DIRECTION",
  na.rm = TRUE
)
n_not_testable <- sum(
  replication$replication_status ==
    "NOT_TESTABLE",
  na.rm = TRUE
)

summary_lines <- c(
  paste0("Accession: ", accession),
  "Role: independent rescue replication",
  "Model: A549",
  "Conditions: DMSO / RSL3 / RSL3+Fer-1",
  "n = 3 per group",
  "",
  "DE model: ~ condition",
  "Primary contrasts:",
  "  RSL3 - DMSO",
  "  RSL3 - (RSL3 + Ferrostatin-1)",
  "",
  paste0("Genes retained after count prefilter: ", nrow(dds)),
  paste0("Frozen GSE182638 ESR candidates: ", nrow(frozen)),
  paste0("Replication support: ", n_support),
  paste0("Replication contradiction: ", n_contradict),
  paste0("Not testable: ", n_not_testable),
  "",
  "Interpretation rule:",
  "  GSE247883 does not select new ESR genes.",
  "  Positive replication_e supports the pre-specified GSE182638 direction plus Fer-1 reversal.",
  "  Negative replication_e contradicts that pre-specified direction.",
  "  Mechanistic-gene acute RNA effects are descriptive; causal role is not treated as an expected acute transcriptional direction."
)

writeLines(
  summary_lines,
  file.path(result_dir, "analysis_summary.txt")
)

capture.output(
  sessionInfo(),
  file = file.path(result_dir, "sessionInfo.txt")
)

message("GSE247883 replication analysis completed.")
message("Results: ", result_dir)
